// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jacpdhsgiuflgoetyrrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphY3BkaHNnaXVmbGdvZXR5cnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5ODY2NDEsImV4cCI6MjA2MDU2MjY0MX0.btNKbnTM_0WyI87a8U_rp8nVjPhCSTN9Iz-ez1q4b88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);